apiVersion: v1
kind: Service
metadata:
  name: edge-iot-server-service
spec:
  type: ClusterIP
  selector:
    app: edge-iot-server-service
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30080
  # type: NodePort